version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-backend
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SERVER_PORT: "8080"
    # Mount đúng file env prod để Spring đọc (application.yaml đã cấu hình import .env.${spring.profiles.active})
    volumes:
      - ./backend/.env.prod:/app/.env.prod:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8080"
        NEXT_PUBLIC_WS_BASE_URL: "http://localhost:8080/ws"
    container_name: finance-frontend
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
