apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: finance
data:
  # KRaft (không cần Zookeeper)
  KAFKA_KRAFT_MODE: "true"
  KAFKA_CLUSTER_ID: "<your-cluster-id>"          # ví dụ: kogIIjc85lesf-mvxBXnHw
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"

  # Listeners
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.finance.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka.finance.svc.cluster.local:9093"

  # Storage & tuning
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_MESSAGE_MAX_BYTES: "200000000"
  KAFKA_REPLICA_FETCH_MAX_BYTES: "200000000"
